In [1]:
%%html
<link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@300;400;500;600;700&display=swap" rel="stylesheet">

<style>
/* markdown + output */
body, .markdown-body, .jp-RenderedHTMLCommon, div.text_cell_render,
.notebook, .notebook * {
  font-family: "Source Serif 4", serif !important;
}

/* code editor (monaco) */
.monaco-editor, .monaco-editor * {
  font-family: "Source Serif 4", serif !important;
}
</style>

In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
os.chdir(r'/Users/proxim/Desktop/CDAC-DBDA-coursework/08.advanced-analytics-stats')

In [4]:
os.getcwd()

'/Users/proxim/Desktop/CDAC-DBDA-coursework/08.advanced-analytics-stats'

In [5]:
df = pd.read_excel('data/CDAC_DataBook.xlsx', sheet_name='ERPData')

In [6]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [7]:
grp1 = df.groupby('Location')

In [8]:
grp1.get_group('MWH-2')

   MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85

In [9]:
grp1.agg(np.sum).Quantity

/var/folders/57/62f2rv1j4w94h8tfp_c43b1c0000gn/T/ipykernel_32758/429834943.py:1: FutureWarning: The provided callable <function sum at 0x106b9c5e0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1.agg(np.sum).Quantity

Location
MWH-1    889
MWH-2    397
MWH-3    174
MWH-4    728
MWH-5    697
Name: Quantity, dtype: int64

In [10]:
grp1.Quantity.agg(['sum','size'])

          sum  size
Location
MWH-1     889    11
MWH-2     397     9
MWH-3     174     4
MWH-4     728    15
MWH-5     697    11

In [11]:
df2 = grp1.agg(np.sum).Quantity

/var/folders/57/62f2rv1j4w94h8tfp_c43b1c0000gn/T/ipykernel_32758/1664439342.py:1: FutureWarning: The provided callable <function sum at 0x106b9c5e0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df2 = grp1.agg(np.sum).Quantity

In [12]:
df2

Location
MWH-1    889
MWH-2    397
MWH-3    174
MWH-4    728
MWH-5    697
Name: Quantity, dtype: int64

In [13]:
df2.shape

(5,)

In [14]:
type(df2)

pandas.core.series.Series

In [15]:
df2 = grp1.agg(np.sum).Quantity.reset_index().rename_axis(columns=None)


# index got renamed it will be removed by rename_axis

/var/folders/57/62f2rv1j4w94h8tfp_c43b1c0000gn/T/ipykernel_32758/1983690337.py:1: FutureWarning: The provided callable <function sum at 0x106b9c5e0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df2 = grp1.agg(np.sum).Quantity.reset_index().rename_axis(columns=None)

In [16]:
df2

  Location  Quantity
0    MWH-1       889
1    MWH-2       397
2    MWH-3       174
3    MWH-4       728
4    MWH-5       697

In [17]:
type(df2)

pandas.core.frame.DataFrame

In [18]:
grp1.Quantity.count().reset_index()

  Location  Quantity
0    MWH-1        11
1    MWH-2         9
2    MWH-3         4
3    MWH-4        15
4    MWH-5        11

In [19]:
grp1.Quantity.sum().reset_index()

  Location  Quantity
0    MWH-1       889
1    MWH-2       397
2    MWH-3       174
3    MWH-4       728
4    MWH-5       697

In [20]:
grp1.Quantity.mean().reset_index()

  Location   Quantity
0    MWH-1  80.818182
1    MWH-2  44.111111
2    MWH-3  43.500000
3    MWH-4  48.533333
4    MWH-5  63.363636

In [21]:
grp2 = df.groupby(['MaterialID', 'Location'])

In [22]:
grp2.groups 

# read as (axcp78, mwh2) combo is occuring in [1, 24, 25, 39, 48] rows

{('AXCP-78', 'MWH-1'): [1, 24, 25, 39, 48], ('AXCP-78', 'MWH-2'): [46], ('AXCP-78', 'MWH-3'): [47], ('AXCP-78', 'MWH-4'): [4], ('AXCP-78', 'MWH-5'): [3, 37, 38], ('DDBN-89', 'MWH-1'): [26, 40, 49], ('DDBN-89', 'MWH-2'): [45], ('DDBN-89', 'MWH-3'): [43], ('DDBN-89', 'MWH-4'): [22, 30], ('DDBN-89', 'MWH-5'): [23], ('GCVB-79', 'MWH-2'): [8, 15, 35, 36], ('GCVB-79', 'MWH-5'): [34], ('LXCV-21', 'MWH-2'): [2], ('LXCV-21', 'MWH-3'): [44], ('LXCV-21', 'MWH-5'): [27, 28, 29], ('SDRT-67', 'MWH-1'): [10, 41], ('SDRT-67', 'MWH-2'): [42], ('SDRT-67', 'MWH-4'): [11], ('SDRT-67', 'MWH-5'): [16, 17], ('TMI-43T', 'MWH-1'): [9], ('TMI-43T', 'MWH-2'): [7], ('TMI-43T', 'MWH-3'): [14], ('TMI-43T', 'MWH-4'): [0, 5, 6, 12, 13, 18, 19, 20, 21, 31, 32], ('TMI-43T', 'MWH-5'): [33]}

In [23]:
grp2.agg([np.sum,np.size])


# axcp78 at mwh5 is total of 200 and at 3 different consignment

/var/folders/57/62f2rv1j4w94h8tfp_c43b1c0000gn/T/ipykernel_32758/3651602171.py:1: FutureWarning: The provided callable <function sum at 0x106b9c5e0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp2.agg([np.sum,np.size])

                    Quantity
                         sum size
MaterialID Location
AXCP-78    MWH-1         548    5
           MWH-2          85    1
           MWH-3          29    1
           MWH-4          36    1
           MWH-5         200    3
DDBN-89    MWH-1         130    3
           MWH-2          69    1
           MWH-3          38    1
           MWH-4          75    2
           MWH-5          71    1
GCVB-79    MWH-2         156    4
           MWH-5          26    1
LXCV-21    MWH-2          27    1
           MWH-3          42    1
           MWH-5         174    3
SDRT-67    MWH-1          91    2
           MWH-2          31    1
           MWH-4          58    1
           MWH-5         114    2
TMI-43T    MWH-1         120    1
           MWH-2          29    1
           MWH-3          65    1
           MWH-4         559   11
           MWH-5         112    1

In [24]:
newdf = grp2.agg([np.sum, np.size])

/var/folders/57/62f2rv1j4w94h8tfp_c43b1c0000gn/T/ipykernel_32758/4092300133.py:1: FutureWarning: The provided callable <function sum at 0x106b9c5e0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  newdf = grp2.agg([np.sum, np.size])

In [25]:
newdf

                    Quantity
                         sum size
MaterialID Location
AXCP-78    MWH-1         548    5
           MWH-2          85    1
           MWH-3          29    1
           MWH-4          36    1
           MWH-5         200    3
DDBN-89    MWH-1         130    3
           MWH-2          69    1
           MWH-3          38    1
           MWH-4          75    2
           MWH-5          71    1
GCVB-79    MWH-2         156    4
           MWH-5          26    1
LXCV-21    MWH-2          27    1
           MWH-3          42    1
           MWH-5         174    3
SDRT-67    MWH-1          91    2
           MWH-2          31    1
           MWH-4          58    1
           MWH-5         114    2
TMI-43T    MWH-1         120    1
           MWH-2          29    1
           MWH-3          65    1
           MWH-4         559   11
           MWH-5         112    1

In [26]:
newdf.loc['AXCP-78']

         Quantity
              sum size
Location
MWH-1         548    5
MWH-2          85    1
MWH-3          29    1
MWH-4          36    1
MWH-5         200    3

In [27]:
newdf.loc[[('LXCV-21', 'MWH-3'),('TMI-43T', 'MWH-2')]]

# This selects and displays the aggregated rows for:
# - MaterialID 'LXCV-21' at Location 'MWH-3'
# - MaterialID 'TMI-43T' at Location 'MWH-2'
# The result shows the sum and size (count) for each numeric column for these specific (MaterialID, Location) pairs.

                    Quantity
                         sum size
MaterialID Location
LXCV-21    MWH-3          42    1
TMI-43T    MWH-2          29    1

In [28]:
newdf.loc[['AXCP-78', 'TMI-43T']]

                    Quantity
                         sum size
MaterialID Location
AXCP-78    MWH-1         548    5
           MWH-2          85    1
           MWH-3          29    1
           MWH-4          36    1
           MWH-5         200    3
TMI-43T    MWH-1         120    1
           MWH-2          29    1
           MWH-3          65    1
           MWH-4         559   11
           MWH-5         112    1

In [29]:
df2 = df.sort_values(['Quantity'], ascending=True)

# single column based sorting

In [30]:
df2.head().reset_index()

   index MaterialID Location  Quantity
0      8    GCVB-79    MWH-2        10
1     16    SDRT-67    MWH-5        12
2     34    GCVB-79    MWH-5        26
3      2    LXCV-21    MWH-2        27
4     30    DDBN-89    MWH-4        27

In [31]:
df2 = df.sort_values(['MaterialID', 'Quantity'], ascending=True)

# two preference sorting

In [32]:
df2.head()

   MaterialID Location  Quantity
47    AXCP-78    MWH-3        29
4     AXCP-78    MWH-4        36
3     AXCP-78    MWH-5        65
37    AXCP-78    MWH-5        65
1     AXCP-78    MWH-1        67

In [33]:
df2 = df.sort_values(['Location','MaterialID','Quantity'], ascending=[False, False, True])

# multi column sorting with ordering preference

# location = desc, materialid = desc, quantity = asc

In [34]:
df2.head()

   MaterialID Location  Quantity
33    TMI-43T    MWH-5       112
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57

In [35]:
b1 = [9,40,80,120,160]
p1 = ['A','B','C','D']
df['Grade'] = pd.cut(df.Quantity, bins=b1, labels=p1)

# This categorizes the 'Quantity' values into bins defined by b1.
# Each bin is labeled with the corresponding value from p1.
# The intervals are:
#   (9, 40]    -> 'A'
#   (40, 80]   -> 'B'
#   (80, 120]  -> 'C'
#   (120, 160] -> 'D'
# Note: The left edge is open and the right edge is closed by default (i.e., 40 is included in 'A', 41 in 'B', etc.).

In [36]:
df.head()

  MaterialID Location  Quantity Grade
0    TMI-43T    MWH-4        34     A
1    AXCP-78    MWH-1        67     B
2    LXCV-21    MWH-2        27     A
3    AXCP-78    MWH-5        65     B
4    AXCP-78    MWH-4        36     A

In [37]:
tz = df.sort_values(['MaterialID', 'Quantity'])

In [38]:
tz.head()

   MaterialID Location  Quantity Grade
47    AXCP-78    MWH-3        29     A
4     AXCP-78    MWH-4        36     A
3     AXCP-78    MWH-5        65     B
37    AXCP-78    MWH-5        65     B
1     AXCP-78    MWH-1        67     B

In [39]:
pune = pd.read_excel('data/CDAC_DataBook.xlsx', sheet_name='Pune')
mumbai = pd.read_excel('data/CDAC_DataBook.xlsx', sheet_name='Mumbai')

In [40]:
pune.head()

      Name      Subject Grade
0   Rakesh       Python     A
1    Manoj     MLPython     C
2  Vaibhav   Statistics     B
3   Hitesh   CommSkills     A
4   Suyash  ProjectMgmt     B

In [41]:
mumbai.head()

       Name     Subject Grade
0   Vaibhav   Six Sigma     A
1   Deepika  Statistics     B
2     Arjun  CommSkills     A
3    Chetan      Python     A
4  Abhishek    MLPython     B

In [42]:
new = pd.merge(pune, mumbai, on='Subject', how='inner')

# by default how = 'inner' (which only gives matching records on subject), we dont even need to specify if that is the case
# so in this case ( on = 'subject )  is good for essentially comparing the marks for the same subject for the different names

In [43]:
new = pd.merge(pune, mumbai, on=['Subject','Grade'])

# so basically the combination of both subject and grade must be common for our output so it will joined based on that

In [44]:
new = pd.merge(pune, mumbai, on=['Subject'], how = 'left')

# this means that the left dataframe shouldn't contain any null records, and only matching from right

In [45]:
new

    Name_x      Subject Grade_x    Name_y Grade_y
0   Rakesh       Python       A    Chetan       A
1    Manoj     MLPython       C  Abhishek       B
2  Vaibhav   Statistics       B   Deepika       B
3   Hitesh   CommSkills       A     Arjun       A
4   Suyash  ProjectMgmt       B       NaN     NaN

In [46]:
new

    Name_x      Subject Grade_x    Name_y Grade_y
0   Rakesh       Python       A    Chetan       A
1    Manoj     MLPython       C  Abhishek       B
2  Vaibhav   Statistics       B   Deepika       B
3   Hitesh   CommSkills       A     Arjun       A
4   Suyash  ProjectMgmt       B       NaN     NaN

In [47]:
new = pd.merge(pune, mumbai, on=['Subject'], how='outer')

# combines both pune and mumbai dataframes, keeping all rows from both, and matches them where 'subject' column records are same otherwise NA

In [48]:
new

    Name_x      Subject Grade_x    Name_y Grade_y
0   Hitesh   CommSkills       A     Arjun       A
1    Manoj     MLPython       C  Abhishek       B
2   Suyash  ProjectMgmt       B       NaN     NaN
3   Rakesh       Python       A    Chetan       A
4      NaN    Six Sigma     NaN   Vaibhav       A
5  Vaibhav   Statistics       B   Deepika       B

In [49]:
d1 = pd.DataFrame({'ID': ['A','B','D'], "Val1":[34,78,67]})
d2 = pd.DataFrame({'ID':['A','B','C','D','E'], "Val2":[30,40,80,20,90]})

In [50]:
pd.merge(d1,d2, how='left')

  ID  Val1  Val2
0  A    34    30
1  B    78    40
2  D    67    20

In [51]:
df = pd.read_excel('data/CDAC_DataBook.xlsx', sheet_name = 'Health')

In [52]:
df.head()

  Country Disease  2019  2020  2021
0   India  Cancer    12    94    35
1      UK  Cancer    95    19    84
2      US  Cancer    98    19    53
3   Japan  Cancer    89    52    14
4   India   Covid    38    19    62

In [53]:
df2 = df.melt(id_vars=['Country', 'Disease'], var_name = 'Year',  value_name = 'Cases')

# id_vars are the columns that we want to keep intact 
# var_name = columns we are melting
# value_name = organizing of the melted columns valuesinto the new column (here 'cases')


# so here values are reorganized by changing the order

In [54]:
df3 = df2.pivot_table(columns='Disease', values='Cases',index=['Country', 'Year'])

# pivot_table is for widening / boradening the table, its exactly opposite for melt

# so basically we are putting the every unique value that comes under the disease to the new individual column

# remember the values in cases comes from the disease column

In [55]:
df3

Disease       Cancer  Covid  Heart Attack
Country Year
India   2019    12.0   38.0          84.0
        2020    94.0   19.0          10.0
        2021    35.0   62.0          98.0
Japan   2019    89.0   14.0          11.0
        2020    52.0   12.0          43.0
        2021    14.0   90.0          75.0
UK      2019    95.0   69.0          44.0
        2020    19.0   73.0          17.0
        2021    84.0   35.0          24.0
US      2019    98.0   87.0          34.0
        2020    19.0   97.0          40.0
        2021    53.0   35.0          54.0

In [56]:
df = pd.read_excel('data/CDAC_DataBook.xlsx', sheet_name='ERPData')

In [57]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [58]:
df1 = df.pivot_table(columns = 'Location', values='Quantity', index='MaterialID').reset_index().rename_axis(columns=None)

In [59]:
df1.head()

  MaterialID       MWH-1  MWH-2  MWH-3  MWH-4      MWH-5
0    AXCP-78  109.600000   85.0   29.0   36.0  66.666667
1    DDBN-89   43.333333   69.0   38.0   37.5  71.000000
2    GCVB-79         NaN   39.0    NaN    NaN  26.000000
3    LXCV-21         NaN   27.0   42.0    NaN  58.000000
4    SDRT-67   45.500000   31.0    NaN   58.0  57.000000

In [60]:
df1 = df.pivot_table(columns = 'Location', values='Quantity', index='MaterialID', aggfunc=np.sum).reset_index().rename_axis(columns=None)

# here aggfunc says count the sums appearances of record, default is mean if not specified

/var/folders/57/62f2rv1j4w94h8tfp_c43b1c0000gn/T/ipykernel_32758/1238229603.py:1: FutureWarning: The provided callable <function sum at 0x106b9c5e0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df1 = df.pivot_table(columns = 'Location', values='Quantity', index='MaterialID', aggfunc=np.sum).reset_index().rename_axis(columns=None)

In [61]:
df1.head()

  MaterialID  MWH-1  MWH-2  MWH-3  MWH-4  MWH-5
0    AXCP-78  548.0   85.0   29.0   36.0  200.0
1    DDBN-89  130.0   69.0   38.0   75.0   71.0
2    GCVB-79    NaN  156.0    NaN    NaN   26.0
3    LXCV-21    NaN   27.0   42.0    NaN  174.0
4    SDRT-67   91.0   31.0    NaN   58.0  114.0

In [62]:
df1 = df.pivot_table(columns = 'Location', values='Quantity', index='MaterialID', aggfunc=np.size).reset_index().rename_axis(columns=None)

# here aggfunc says count the total appearances of record

In [63]:
df1.head()

  MaterialID  MWH-1  MWH-2  MWH-3  MWH-4  MWH-5
0    AXCP-78    5.0    1.0    1.0    1.0    3.0
1    DDBN-89    3.0    1.0    1.0    2.0    1.0
2    GCVB-79    NaN    4.0    NaN    NaN    1.0
3    LXCV-21    NaN    1.0    1.0    NaN    3.0
4    SDRT-67    2.0    1.0    NaN    1.0    2.0

---